In [1]:
import numpy as np

# 주어진 행렬 A와 벡터 b 정의
A = np.array([[1, 1],
              [0, 1]])

b = np.array([1, 2])

# 행렬 A와 벡터 b의 곱 계산
result = np.dot(A, b)

# 결과 출력
print(result)

[3 2]


In [2]:
import numpy as np

# 주어진 행렬 A 정의
A = np.array([[1, 1],
              [-2, 4]])

# eigenvalue와 eigenvector 계산
eigenvalues, eigenvectors = np.linalg.eig(A)

In [3]:
print(eigenvalues)

[2. 3.]


In [4]:
print(eigenvectors)

[[-0.70710678 -0.4472136 ]
 [-0.70710678 -0.89442719]]


In [5]:
for i in range(len(eigenvalues)):
    print("Eigenvalue {}: {}".format(i+1, eigenvalues[i]))
    print("Eigenvector {}: {}".format(i+1, eigenvectors[:, i]))
    print()

Eigenvalue 1: 2.0
Eigenvector 1: [-0.70710678 -0.70710678]

Eigenvalue 2: 3.0
Eigenvector 2: [-0.4472136  -0.89442719]



In [6]:
import numpy as np

# 3차원 행렬 로  eigen 값 구하는 연습 (추가)
A = np.array([[2, -1, 0],
              [-1, 2, -1],
              [0, -1, 2]])

# 행렬 A의 고유값(eigenvalue)과 고유벡터(eigenvector) 계산
eigenvalues, eigenvectors = np.linalg.eig(A)

# 결과 출력
for i in range(len(eigenvalues)):
    print("Eigenvalue {}: {}".format(i+1, eigenvalues[i]))
    print("Eigenvector {}: {}".format(i+1, eigenvectors[:, i]))
    print()

Eigenvalue 1: 3.4142135623730914
Eigenvector 1: [-0.5         0.70710678 -0.5       ]

Eigenvalue 2: 1.9999999999999998
Eigenvector 2: [-7.07106781e-01  4.05405432e-16  7.07106781e-01]

Eigenvalue 3: 0.5857864376269049
Eigenvector 3: [0.5        0.70710678 0.5       ]



In [7]:
import numpy as np

# 주어진 행렬 A 정의
A = np.array([[1, 2, 0],
              [0, 3, 0],
              [2, -4, 2]])

# 행렬 A의 eigenvalue와 eigenvector 계산
eigenvalues, eigenvectors = np.linalg.eig(A)

# 대각 행렬 D 생성
D = np.diag(eigenvalues)

# 대각화된 행렬 계산
A_diagonalized = np.dot(np.dot(np.linalg.inv(eigenvectors), A), eigenvectors)

# 결과 출력
print("Diagonalized Matrix:")
print(A_diagonalized)


Diagonalized Matrix:
[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 3.]]


In [8]:
import numpy as np

# 주어진 행렬 A 정의
A = np.array([[7, 2],
              [2, 4]])

# 행렬 A의 eigenvalue와 eigenvector 계산
eigenvalues, eigenvectors = np.linalg.eig(A)

# spectrum decomposition을 위한 대각 행렬 D 생성
D = np.diag(eigenvalues)

# 첫 번째 행렬로 쪼개지는 부분 계산
first_matrix = np.outer(eigenvectors[:, 0], eigenvectors[:, 0]) * eigenvalues[0]

# 두 번째 행렬로 쪼개지는 부분 계산
second_matrix = np.outer(eigenvectors[:, 1], eigenvectors[:, 1]) * eigenvalues[1]

# 결과 출력
print("First Matrix:")
print(first_matrix)
print()
print("Second Matrix:")
print(second_matrix)

First Matrix:
[[6.4 3.2]
 [3.2 1.6]]

Second Matrix:
[[ 0.6 -1.2]
 [-1.2  2.4]]


In [9]:
import numpy as np

# 주어진 3차원 행렬 정의
A = np.array([[3, 2],
              [1, 2],
              [-4, 0],
              [0, -4]])

# 행렬 A의 SVD(Singular Value Decomposition) 계산
U, S, Vt = np.linalg.svd(A)

# 결과 출력
print("U:")
print(U)
print("S:")
print(S)
print("Vt:")
print(Vt)


U:
[[-0.62133091  0.11810122  0.77424974  0.02318059]
 [-0.36057233 -0.20350962 -0.28420481  0.86475375]
 [ 0.52151716 -0.64322168  0.5096361   0.23357388]
 [ 0.46038608  0.72863009  0.24502247  0.44396717]]
S:
[5.74997893 4.11554884]
Vt:
[[-0.74967818 -0.66180256]
 [ 0.66180256 -0.74967818]]
